// Code generated by "stringer -type Token"; DO NOT EDIT.

package expr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[IDENT-1]
	_ = x[INT-2]
	_ = x[FLOAT-3]
	_ = x[FIELD-4]
	_ = x[ADD-5]
	_ = x[SUB-6]
	_ = x[MUL-7]
	_ = x[QUO-8]
	_ = x[REM-9]
	_ = x[DOL-10]
	_ = x[LSS-11]
	_ = x[GTR-12]
	_ = x[EQL-13]
	_ = x[NEQ-14]
	_ = x[LEQ-15]
	_ = x[GEQ-16]
	_ = x[LAND-17]
	_ = x[LOR-18]
	_ = x[AND-19]
	_ = x[OR-20]
	_ = x[NOT-21]
	_ = x[LPAREN-22]
	_ = x[COMMA-23]
	_ = x[RPAREN-24]
	_ = x[EOF-25]
}

const _Token_name = "INVALIDIDENTINTFLOATFIELDADDSUBMULQUOREMDOLLSSGTREQLNEQLEQGEQLANDLORANDORNOTLPARENCOMMARPARENEOF"

var _Token_index = [...]uint8{0, 7, 12, 15, 20, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 65, 68, 71, 73, 76, 82, 87, 93, 96}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
